// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellView = { row: number, col: number, value: number | null, notes: Array<number>, fixed: boolean, selected: boolean, highlighted: boolean, sameBox: boolean, sameValue: boolean, invalid: boolean, };
