// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellView } from "./CellView";
import type { Difficulty } from "./Difficulty";
import type { GameStatus } from "./GameStatus";
import type { InputMode } from "./InputMode";
import type { PositionView } from "./PositionView";
import type { RecapView } from "./RecapView";
import type { ValidationMode } from "./ValidationMode";

export type GameView = { started: boolean, status: GameStatus, inputMode: InputMode, validationMode: ValidationMode, difficulty: Difficulty, cells: Array<Array<CellView>>, selected: Array<PositionView>, canSubmit: boolean, canClear: boolean, showComplete: boolean, recap: RecapView | null, };
